Repository JohanCDev/Gomoku, pull requests merged in 2022-11, with the labels that each got.

#23 rtor: fix makefile with cp
  Makefile
  src/pbrain-gomoku-ai.py
Labels: bug

#27 Start Command implemented, closes #1
  src/Game.py
Labels: documentation, command, Mandatory

#28 add: Handle basically BEGIN command
  src/Game.py
Labels: command, Mandatory, Brain Answer

#29 Commands: End and Turn
  src/Game.py
Labels: command, Mandatory, Brain Answer

#31 BOARD Command Done
  src/Game.py
  src/utils/PrintGomoku.py
Labels: command, Mandatory, Brain Answer

#32 14 create board class
  Makefile
  src/Game.py
  src/GomokuBoard.py
  tests/GomokuBoardTests.py
  tests/GomokuTests.py
  tests/ParserTests.py
Labels: Mandatory, Algorithm

#34 Hotfix : Board Command
  src/Game.py
  src/ParseInput.py
Labels: bug, command, Mandatory, Brain Answer

#37 35 update board with commands
  src/Game.py
  src/GomokuBoard.py
  src/ParseInput.py
  tests/GomokuBoardTests.py
  tests/ParserTests.py
Labels: command, Mandatory, Manager command, Brain Answer

#41 Naïve Simple line
  src/Brain.py
  src/Game.py
  tests/CheckWinTests.py
  tests/scripts/basicLooseLine.txt
  tests/scripts/basicLooseLineReversed.txt
  tests/scripts/basicVictoryLine.txt
  tests/scripts/basicVictoryLineReverse.txt
Labels: command, Brain Answer, AI

#43 Min Max algorithm
  src/Brain.py
  src/GomokuBoard.py
Labels: Algorithm, AI
